---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false

title: "G Security Desktop Locker"
description: "G Security is an easy to use, freeware, fast, secure, advance and compact desktop locker, screen locker developed for Microsoft Windows by Leo Softwares Pakistan"
keywords: "screen locker, desktop locker, windows free locker, secure locking software, windows locking software freeware, Pakistan, malik usman aura, best locking program, free download"
email: usmanaura47@gmail.com
baseurl: "/gsecuritylocker-web" # the subpath of your site, e.g. /blog
favicon:     "favicon.ico"
touch_icon:  "apple-touch-icon.png"
google_analytics_key: "" ## put YOUR key here to enable tracking! (blank to disable)

url: ""
enforce_ssl: ""

twitter:
  username: malikusmanaura
  image: "{{ site.baseurl }}/img/gsecurity-logo.png"
  
image: 
  path: "/img/gsecurity-logo.png"

logo: "/img/gsecurity-logo.png"

author: "Malik Usman Aura"
social:
  name: Malik Usman Aura
  links:
    - https://twitter.com/malikusmanaura
    - https://www.facebook.com/malikusman.aura
    - https://pk.linkedin.com/in/malikusmanaura
    - https://plus.google.com/+MalikUsmanAura
    - https://github.com/usmanaura47
    - https://sourceforge.net/u/usman47
    
# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
